"""
Skill Verifier AI LLM Question Generator
Integrates with OpenAI and Google Gemini APIs to dynamically craft personalized,
anti-AI diagnostic question papers based on developer GitHub repositories and languages.
"""

import json
import os
import re
from typing import Any, Optional

import httpx

OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "").strip()
GEMINI_API_KEY = os.getenv("GEMINI_API_KEY", "").strip()
OPENAI_MODEL = os.getenv("OPENAI_MODEL", "gpt-4o-mini").strip()


def _clean_json_response(raw_text: str) -> str:
    """Removes markdown backticks and extracts pure JSON content."""
    text = raw_text.strip()
    if text.startswith("```"):
        text = re.sub(r"^```[a-zA-Z]*\n", "", text)
        text = re.sub(r"\n```$", "", text)
    return text.strip()


async def generate_questions_with_openai(
    language: str,
    context: Optional[dict[str, Any]] = None,
    count: int = 10,
) -> Optional[list[dict[str, Any]]]:
    """Generates dynamic diagnostic questions using OpenAI Chat Completions API."""
    api_key = os.getenv("OPENAI_API_KEY", OPENAI_API_KEY).strip()
    if not api_key:
        return None

    username = context.get("username", "developer") if context else "developer"
    repos = context.get("repo_names", []) if context else []
    repo_mention = f"The developer's real repositories include: {', '.join(repos[:4])}." if repos else ""

    prompt = (
        f"You are a Principal Systems Engineer and technical interviewer evaluating candidate @{username}. "
        f"Their strongest language extracted from their public GitHub profile is '{language}'. {repo_mention}\n\n"
        f"Task: Generate exactly {count} tricky, diagnostic, anti-AI multiple-choice questions designed "
        f"to test whether @{username} genuinely understands low-level mechanics, memory lifecycles, "
        f"execution semantics, and edge cases in {language}, or if their repository code was merely "
        f"generated by AI (ChatGPT/Copilot) or copy-pasted without deep human understanding.\n\n"
        f"Calibration Requirements:\n"
        f"- Target authentic language gotchas (e.g. pointer decay, memory alignment, closures, GIL, event loop, "
        f"type coercion, borrow checker, slice headers, sequence points, mutable defaults, autoboxing cache).\n"
        f"- Every question MUST include a concise code snippet demonstrating the trap.\n"
        f"- Exactly 4 plausible options for each question.\n"
        f"- 'correctIndex' must be an integer (0, 1, 2, or 3) pointing to the true option.\n"
        f"- Provide an in-depth 'explanation' revealing the internal compiler or runtime reason.\n"
        f"- Format strictly as a valid JSON array of objects with keys: "
        f"['question', 'difficulty', 'concept', 'codeSnippet', 'options', 'correctIndex', 'explanation']."
    )

    try:
        async with httpx.AsyncClient(timeout=25.0) as client:
            resp = await client.post(
                "https://api.openai.com/v1/chat/completions",
                headers={
                    "Authorization": f"Bearer {api_key}",
                    "Content-Type": "application/json",
                },
                json={
                    "model": OPENAI_MODEL,
                    "messages": [
                        {
                            "role": "system",
                            "content": "You output only strictly valid JSON matching the requested schema without any markdown commentary.",
                        },
                        {"role": "user", "content": prompt},
                    ],
                    "temperature": 0.7,
                },
            )
            if resp.status_code != 200:
                return None

            data = resp.json()
            content = data["choices"][0]["message"]["content"]
            cleaned = _clean_json_response(content)
            parsed = json.loads(cleaned)
            if isinstance(parsed, list) and len(parsed) >= count:
                for idx, q in enumerate(parsed[:count], start=1):
                    q["id"] = idx
                return parsed[:count]
    except Exception:
        return None

    return None


async def generate_questions_with_gemini(
    language: str,
    context: Optional[dict[str, Any]] = None,
    count: int = 10,
) -> Optional[list[dict[str, Any]]]:
    """Generates dynamic diagnostic questions using Google Gemini REST API."""
    api_key = os.getenv("GEMINI_API_KEY", GEMINI_API_KEY).strip()
    if not api_key:
        return None

    username = context.get("username", "developer") if context else "developer"
    repos = context.get("repo_names", []) if context else []
    repo_mention = f"Real repos: {', '.join(repos[:4])}." if repos else ""

    prompt = (
        f"Generate {count} multiple-choice anti-AI diagnostic questions for '{language}' for candidate @{username}. {repo_mention}\n"
        f"Focus on deep mechanics, memory hazards, and compiler traps that distinguish authentic developers from AI prompt-copiers.\n"
        f"Return ONLY a JSON array of objects with keys: "
        f"['question', 'difficulty', 'concept', 'codeSnippet', 'options' (array of 4 strings), 'correctIndex' (0-3), 'explanation']."
    )

    url = f"https://generativelanguage.googleapis.com/v1beta/models/gemini-1.5-flash:generateContent?key={api_key}"
    try:
        async with httpx.AsyncClient(timeout=25.0) as client:
            resp = await client.post(
                url,
                headers={"Content-Type": "application/json"},
                json={
                    "contents": [{"parts": [{"text": prompt}]}],
                    "generationConfig": {"temperature": 0.7, "responseMimeType": "application/json"},
                },
            )
            if resp.status_code != 200:
                return None

            data = resp.json()
            raw_text = data["candidates"][0]["content"]["parts"][0]["text"]
            cleaned = _clean_json_response(raw_text)
            parsed = json.loads(cleaned)
            if isinstance(parsed, list) and len(parsed) >= count:
                for idx, q in enumerate(parsed[:count], start=1):
                    q["id"] = idx
                return parsed[:count]
    except Exception:
        return None

    return None


async def generate_dynamic_ai_questions(
    language: str,
    context: Optional[dict[str, Any]] = None,
    count: int = 10,
) -> Optional[tuple[list[dict[str, Any]], str]]:
    """
    Attempts OpenAI first, then Gemini if configured.
    Returns (questions, 'openai'|'gemini') if successful, else None.
    """
    if os.getenv("OPENAI_API_KEY", OPENAI_API_KEY).strip():
        qs = await generate_questions_with_openai(language, context, count)
        if qs:
            return qs, "ai_openai"

    if os.getenv("GEMINI_API_KEY", GEMINI_API_KEY).strip():
        qs = await generate_questions_with_gemini(language, context, count)
        if qs:
            return qs, "ai_gemini"

    return None
